---
- hosts: localhost
  vars:
    description: “Query VCenter for a VM”
    vc_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    vc_username: "{{ lookup('env', 'VMWARE_USER') }}"
    vc_passwd: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    dcenter: datacentername
    vm_name: vmname
  tasks:
  - name: find the folder for a VM
    vmware_guest_find:
      hostname: '{{ vc_hostname }}'
      username: '{{ vc_username }}'
      password: '{{ vc_passwd }}'
      datacenter: '{{ dcenter }}'
      validate_certs: no
      name: '{{ vm_name }}'
    delegate_to: localhost
    register: facts
  - debug:
      var: facts
