---
- hosts: localhost
  vars:
    description: “this is a leaf switch”
  tasks:
  - name: get vm facts
    vmware_guest_facts:
      hostname: 192.168.1.209
      username: administrator@vsphere.local
      password: vmware
      datacenter: ha-datacenter
      validate_certs: no
      uuid: 421e4592-c069-924d-ce20-7e7533fab926
    delegate_to: localhost
    register: facts
