---
- hosts: localhost
  vars:
    description: “Test VSphere Connectivity”
    vc_hostname: vcenterhostname
    vc_username: vcenterusername
    vc_passwd: vcenterpassword
    dcenter: datacentername
    vm_name: vmname
    vm_folder: /DCA/vm/Cloudforms
  tasks:
  - name: get vm facts
    vmware_guest_facts:
      hostname: vcentera.atpiad1.local
      username: atpiad1\disapiuser
      password: '@p1r3@d0n1Y4D1$'
      datacenter: '{{ dcenter }}' 
      validate_certs: no
      name: '{{ vm_name }}'
      folder: '{{ vm_folder }}'
    delegate_to: localhost
    register: facts
