---
- hosts: localhost
  pre_tasks:
    - include_vars: provision_ose_manifest.yml
  vars:
    vars:
    description: “Get facts from VCenter”
    vc_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    vc_username: "{{ lookup('env', 'VMWARE_USER') }}"
    vc_passwd: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    dcenter: "{{ data_center }}"
    servers: "{{ infra_servers }}"
    vm_nodename: "{{ vm_host }}"
    vm_nw: "{{ vm_nw }}"
    vm_nw_gateway: "{{ vm_nw_gateway }}"
    vm_nw_domain: "{{ vm_nw_domain }}"
    vm_nw_netmask: "{{ vm_nw_netmask }}"
    vm_nw_type: "{{ vm_nw_type }}"
    vm_nw_dns: "{{ vm_nw_dns }}"
    vm_nw_dns_search: "{{ vm_nw_dns_search }}"
  tasks:
  - name: Provision cluster nodes
    vmware_guest:
      validate_certs: False
      hostname: "{{ vc_hostname }}"
      username: "{{ vc_username }}"
      password: "{{ vc_passwd }}"
      name: "{{ item.server_name }}"
      state: poweredon
      folder: "{{ item.folder }}"
      disk: " {{ item.disk }}"
      hardware:
          memory_mb: 512
          num_cpus: 1
          osid: centos64guest
          scsi: paravirtual
      datacenter: "{{ dcenter }}"
      esxi_hostname: "{{ vm_nodename }}"
      template: "{{ item.template_name }}"
      networks: "{{ item.networks }}"
      wait_for_ip_address: no
      customization:
        dns_servers: "{{ vm_nw_dns }}"
        dns_suffix: "{{ vm_nw_dns_search }}"
    with_items: "{{ servers }}"
    register: facts
  - debug:
      var: facts
