---
- hosts: all
  pre_tasks:
    - include_vars: provision_ose_manifest.yml
  vars:
    vars:
    description: “Get facts from VCenter”
    vc_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    vc_username: "{{ lookup('env', 'VMWARE_USER') }}"
    vc_passwd: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    dcenter: Lab
    servers: "{{ master_servers }}"
  tasks:
  - name: get vm facts
    vmware_guest_facts:
      hostname: '{{ vc_hostname }}'
      username: '{{ vc_username }}'
      password: '{{ vc_passwd }}'
      datacenter: '{{ dcenter }}' 
      validate_certs: no
      name: '{{ item.server_name }}'
      folder: '{{ item.folder }}'
    delegate_to: localhost
    with_items: "{{ servers }}"
    register: facts
  - debug:
      var: facts
