---
- hosts: localhost
  vars:
    description: “Provision a VM from a template”
    vc_hostname: vcenterhostname
    vc_username: vcenterusername
    vc_passwd: vcenterpassword
    dcenter: datacentername
    vm_name: vmname
    vm_folder: /DCA/vm/CloudForms
    vm_datastore: ExternalDS-13
    vm_nodename: 172.16.5.13
    vm_template: baselineTemplate
  tasks:
    - name: create the VM
      vmware_guest:
        validate_certs: False
        hostname: "{{ vc_hostname }}"
        username: "{{ vc_username }}"
        password: "{{ vc_passwd }}"
        name: "{{ vm_name }}"
        state: poweredon
        folder: "{{ vm_folder }}"
        disk:
        - size_gb: 20
          type: thin
          datastore: ExternalDS-13
        hardware:
            memory_mb: 512
            num_cpus: 2
            osid: centos64guest
            scsi: paravirtual
        datacenter: "{{ dcenter }}"
        esxi_hostname: "{{ vm_nodename }}"
        template: "{{ vm_template }}"
        wait_for_ip_address: yes
        customization:
          password: smartvm
      register: deploy

