---
- hosts: localhost
  pre_tasks:
    - include_vars: provision_ose_manifest.yml
  vars:
    vars:
    description: “Get facts from VCenter”
    vc_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    vc_username: "{{ lookup('env', 'VMWARE_USER') }}"
    vc_passwd: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    dcenter: "{{ data_center }}"
    servers: "{{ master_servers }}"
    vm_nodename: "{{ vm_host }}"
    vm_nw: "{{ vm_nw }}"
    vm_nw_gateway: "{{ vm_nw_gateway }}"
    vm_nw_domain: "{{ vm_nw_domain }}"
    vm_nw_netmask: "{{ vm_nw_netmask }}"
    vm_nw_type: "{{ vm_nw_type }}"
  tasks:
  - name: Provision cluster nodes
    vmware_guest:
      validate_certs: False
      hostname: "{{ vc_hostname }}"
      username: "{{ vc_username }}"
      password: "{{ vc_passwd }}"
      name: "{{ item.server_name }}"
      state: poweredon
      folder: "{{ item.folder }}"
      disk:
      - size_gb: 16
        type: thin
        datastore: ExternalDS-13
      hardware:
          memory_mb: 512
          num_cpus: 1
          osid: centos64guest
          scsi: paravirtual
      datacenter: "{{ dcenter }}"
      esxi_hostname: "{{ vm_nodename }}"
      template: "{{ item.template_name }}"
      networks:
      - name: "{{ item.vm_nw }}"
        ip: "{{ item.ip_address }}"
        netmask: "{{ vm_nw_netmask }}"
        gateway: "{{ vm_nw_gateway }}"
        domain: "{{ vm_nw_domain }}"
        dns_servers:
        - 75.75.75.75
        - 8.8.8.8
        type: "{{ vm_nw_type }}"
      wait_for_ip_address: yes
    with_items: "{{ servers }}"
    register: facts
  - debug:
      var: facts
