---
- hosts: localhost
  vars:
    description: “Delete a VM”
    vc_hostname: vcenterhostname
    vc_username: vcenterusername
    vc_passwd: vcenterpassword
    dcenter: datacentername
    vm_name: vmname
    vm_folder: /DCA/vm/CloudForms
    vm_datastore: ExternalDS-13
    vm_nodename: 172.16.5.13
  tasks:
    - name: create the VM
      vmware_guest:
        hostname: "{{ vc_hostname }}"
        username: "{{ vc_username }}"
        password: "{{ vc_passwd }}"
        name: "{{ vm_name }}"
        folder: "{{ vm_folder }}"
        datacenter: "{{ dcenter }}"
        validate_certs: no
        esxi_hostname: "{{ vm_nodename }}"
        state: absent
      register: deploy

