---
- hosts: localhost
  vars:
    description: “Delete a VM”
    vc_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    vc_username: "{{ lookup('env', 'VMWARE_USER') }}"
    vc_passwd: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    vm_name: vmname
  tasks:
    - name: Shutdown VM first if delete required
      vmware_guest:
        validate_certs: False
        hostname: "{{ vc_hostname }}"
        username: "{{ vc_username }}"
        password: "{{ vc_passwd }}"
        name: "{{ vm_name }}"
        state: "poweredoff"
        template: ""
    when: state == "absent"

  - name: Set VM to desired state
    vmware_guest:
      validate_certs: False
      hostname: "{{ vc_hostname }}"
      username: "{{ vc_username }}"
      password: "{{ vc_passwd }}"
      name: "{{ vm_name }}"
      state: "{{ state }}"
      template: ""
